name: gamma_cicd
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"  # Ubah ke 3.1.0 untuk kompatibilitas dengan flutter_lints 4.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0   # Turunkan ke versi 3.x yang kompatibel dengan Dart 3.1.x

flutter:
  uses-material-design: true