name: Build Flutter APK

on:
  push:
    branches: [main] # atau ganti dengan branch yang kamu pakai
  workflow_dispatch: # biar bisa manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2' # ganti sesuai pubspec.yaml kamu

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # OPTIONAL: Kirim ke Telegram
      - name: Send to Telegram
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          document: build/app/outputs/flutter-apk/app-release.apk
          message: "🎉 Build APK selesai!\nProject: gamma_cicd"
