name: Build APK Flutter and Send Telegram

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'

      - name: Check Flutter version and environment
        run: |
          flutter --version
          flutter doctor -v

      - name: Clean Flutter build (optional, tapi direkomendasikan)
        run: flutter clean

      - name: Clear Flutter Pub Cache
        run: flutter pub cache repair

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Setup Node.js (optional, required for some actions)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Send APK to Telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          document: build/app/outputs/flutter-apk/app-release.apk
          message: "🎉 Build APK berhasil! Project: gamma_cicd"
